import React, { createContext, useContext, useEffect, useState, useCallback } from 'react';

type Language = 'pl' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pl: {
    'nav.dashboard': 'Panel',
    'nav.tasks': 'Zadania',
    'nav.shopping': 'Zakupy',
    'nav.habits': 'Nawyki',
    'nav.notes': 'Notatki',
    'nav.budget': 'Budżet',
    'nav.plan': 'Plan',
    'nav.calendar': 'Kalendarz',
    'nav.meals': 'Posiłki',
    'nav.mood': 'Nastrój',
    'nav.chat': 'Czat',
    'nav.settings': 'Ustawienia',
    'auth.login': 'Zaloguj się',
    'auth.register': 'Zarejestruj się',
    'auth.email': 'Email',
    'auth.password': 'Hasło',
    'auth.forgotPassword': 'Zapomniałeś hasła?',
    'auth.loginWithGoogle': 'Zaloguj przez Google',
    'auth.createAccount': 'Załóż konto',
    'auth.alreadyHaveAccount': 'Masz już konto?',
    'auth.dontHaveAccount': 'Nie masz konta?',
    'auth.signUp': 'Zarejestruj się',
    'auth.signIn': 'Zaloguj się',
    'common.save': 'Zapisz',
    'common.cancel': 'Anuluj',
    'common.delete': 'Usuń',
    'common.edit': 'Edytuj',
    'common.add': 'Dodaj',
    'common.loading': 'Ładowanie...',
    'common.error': 'Błąd',
    'common.success': 'Sukces',
    'common.close': 'Zamknij',
    'common.confirm': 'Potwierdź',
    'common.back': 'Wróć',
    'common.next': 'Dalej',
    'common.done': 'Gotowe',
    'common.search': 'Szukaj',
    'common.filter': 'Filtruj',
    'common.sort': 'Sortuj',
    'dashboard.title': 'Witaj z powrotem',
    'dashboard.subtitle': 'Twój osobisty asystent produktywności',
    'dashboard.todayTasks': 'Dzisiejsze zadania',
    'dashboard.upcomingEvents': 'Nadchodzące wydarzenia',
    'dashboard.quickActions': 'Szybkie akcje',
    'dashboard.recentNotes': 'Ostatnie notatki',
    'dashboard.budgetOverview': 'Przegląd budżetu',
    'dashboard.habitProgress': 'Postęp nawyków',
    'tasks.title': 'Zadania',
    'tasks.addTask': 'Dodaj zadanie',
    'tasks.taskTitle': 'Tytuł zadania',
    'tasks.description': 'Opis',
    'tasks.dueDate': 'Termin',
    'tasks.priority': 'Priorytet',
    'tasks.status': 'Status',
    'tasks.high': 'Wysoki',
    'tasks.medium': 'Średni',
    'tasks.low': 'Niski',
    'tasks.completed': 'Ukończone',
    'tasks.pending': 'Oczekujące',
    'tasks.inProgress': 'W trakcie',
    'settings.title': 'Ustawienia',
    'settings.subtitle': 'Dostosuj LifeFlow do swoich potrzeb i preferencji.',
    'settings.profile': 'Profil',
    'settings.appearance': 'Wygląd',
    'settings.notifications': 'Powiadomienia',
    'settings.privacy': 'Prywatność',
    'settings.language': 'Język',
    'settings.ai': 'Sztuczna Inteligencja',
    'settings.ai.subtitle': 'Zarządzaj mocą AI i asystentami',
    'settings.notifications.subtitle': 'Zarządzaj alertami i przypomnieniami',
    'settings.appearance.subtitle': 'Motyw ciemny, jasny i kolory akcentów',
    'settings.theme': 'Motyw',
    'settings.export': 'Eksport danych',
    'settings.about': 'O aplikacji',
    'settings.help': 'Pomoc',
    'settings.subscription': 'Subskrypcja',
    'settings.subscription.subtitle': 'LifeFlow Premium - Aktywna',
    'settings.defaultUser': 'Użytkownik LifeFlow',
    'settings.editProfile': 'Edytuj profil',
    'budget.title': 'Budżet',
    'budget.income': 'Przychody',
    'budget.expenses': 'Wydatki',
    'budget.balance': 'Saldo',
    'budget.addTransaction': 'Dodaj transakcję',
    'budget.amount': 'Kwota',
    'budget.category': 'Kategoria',
    'budget.description': 'Opis',
    'calendar.title': 'Kalendarz',
    'calendar.today': 'Dziś',
    'calendar.week': 'Tydzień',
    'calendar.month': 'Miesiąc',
    'calendar.addEvent': 'Dodaj wydarzenie',
    'calendar.eventTitle': 'Tytuł wydarzenia',
    'calendar.startTime': 'Czas rozpoczęcia',
    'calendar.endTime': 'Czas zakończenia',
    'habits.title': 'Nawyki',
    'habits.addHabit': 'Dodaj nawyk',
    'habits.habitName': 'Nazwa nawyku',
    'habits.frequency': 'Częstotliwość',
    'habits.daily': 'Codziennie',
    'habits.weekly': 'Co tydzień',
    'habits.monthly': 'Co miesiąc',
    'habits.streak': 'Seria',
    'notes.title': 'Notatki',
    'notes.addNote': 'Dodaj notatkę',
    'notes.noteTitle': 'Tytuł notatki',
    'notes.noteContent': 'Treść notatki',
    'notes.search': 'Szukaj notatek',
    'shopping.title': 'Zakupy',
    'shopping.addItem': 'Dodaj produkt',
    'shopping.itemName': 'Nazwa produktu',
    'shopping.quantity': 'Ilość',
    'shopping.price': 'Cena',
    'shopping.category': 'Kategoria',
    'shopping.purchased': 'Kupione',
    'chat.title': 'Czat AI',
    'chat.typeMessage': 'Wpisz wiadomość...',
    'chat.send': 'Wyślij',
    'chat.aiAssistant': 'Asystent AI',
    'mood.title': 'Nastrój',
    'mood.today': 'Dzisiejszy nastrój',
    'mood.addEntry': 'Dodaj wpis',
    'mood.note': 'Notatka',
    'meals.title': 'Planer posiłków',
    'meals.addMeal': 'Dodaj posiłek',
    'meals.mealName': 'Nazwa posiłku',
    'meals.calories': 'Kalorie',
    'meals.mealType': 'Rodzaj posiłku',
    'error.network': 'Błąd sieci',
    'error.auth': 'Błąd autentykacji',
    'error.validation': 'Błąd walidacji',
    'error.unknown': 'Nieznany błąd',
    'error.emailRequired': 'Email jest wymagany',
    'error.passwordRequired': 'Hasło jest wymagane',
    'error.invalidEmail': 'Nieprawidłowy email',
    'error.weakPassword': 'Hasło jest zbyt słabe',
    'success.saved': 'Zapisano',
    'success.deleted': 'Usunięto',
    'success.updated': 'Zaktualizowano',
    'success.added': 'Dodano',
    'time.today': 'Dziś',
    'time.yesterday': 'Wczoraj',
    'time.tomorrow': 'Jutro',
    'time.thisWeek': 'W tym tygodniu',
    'time.thisMonth': 'W tym miesiącu',
    'time.lastWeek': 'Ostatni tydzień',
    'time.lastMonth': 'Ostatni miesiąc',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Tasks',
    'nav.shopping': 'Shopping',
    'nav.habits': 'Habits',
    'nav.notes': 'Notes',
    'nav.budget': 'Budget',
    'nav.plan': 'Plan',
    'nav.calendar': 'Calendar',
    'nav.meals': 'Meals',
    'nav.mood': 'Mood',
    'nav.chat': 'Chat',
    'nav.settings': 'Settings',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loginWithGoogle': 'Login with Google',
    'auth.createAccount': 'Create account',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signUp': 'Sign up',
    'auth.signIn': 'Sign in',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.done': 'Done',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'dashboard.title': 'Welcome back',
    'dashboard.subtitle': 'Your personal productivity assistant',
    'dashboard.todayTasks': "Today's tasks",
    'dashboard.upcomingEvents': 'Upcoming events',
    'dashboard.quickActions': 'Quick actions',
    'dashboard.recentNotes': 'Recent notes',
    'dashboard.budgetOverview': 'Budget overview',
    'dashboard.habitProgress': 'Habit progress',
    'tasks.title': 'Tasks',
    'tasks.addTask': 'Add task',
    'tasks.taskTitle': 'Task title',
    'tasks.description': 'Description',
    'tasks.dueDate': 'Due date',
    'tasks.priority': 'Priority',
    'tasks.status': 'Status',
    'tasks.high': 'High',
    'tasks.medium': 'Medium',
    'tasks.low': 'Low',
    'tasks.completed': 'Completed',
    'tasks.pending': 'Pending',
    'tasks.inProgress': 'In progress',
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize LifeFlow to your needs and preferences.',
    'settings.profile': 'Profile',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.language': 'Language',
    'settings.ai': 'Artificial Intelligence',
    'settings.ai.subtitle': 'Manage AI power and assistants',
    'settings.notifications.subtitle': 'Manage alerts and reminders',
    'settings.appearance.subtitle': 'Dark theme, light theme and accent colors',
    'settings.theme': 'Theme',
    'settings.export': 'Export data',
    'settings.about': 'About',
    'settings.help': 'Help',
    'settings.subscription': 'Subscription',
    'settings.subscription.subtitle': 'LifeFlow Premium - Active',
    'settings.defaultUser': 'LifeFlow User',
    'settings.editProfile': 'Edit Profile',
    'budget.title': 'Budget',
    'budget.income': 'Income',
    'budget.expenses': 'Expenses',
    'budget.balance': 'Balance',
    'budget.addTransaction': 'Add transaction',
    'budget.amount': 'Amount',
    'budget.category': 'Category',
    'budget.description': 'Description',
    'calendar.title': 'Calendar',
    'calendar.today': 'Today',
    'calendar.week': 'Week',
    'calendar.month': 'Month',
    'calendar.addEvent': 'Add event',
    'calendar.eventTitle': 'Event title',
    'calendar.startTime': 'Start time',
    'calendar.endTime': 'End time',
    'habits.title': 'Habits',
    'habits.addHabit': 'Add habit',
    'habits.habitName': 'Habit name',
    'habits.frequency': 'Frequency',
    'habits.daily': 'Daily',
    'habits.weekly': 'Weekly',
    'habits.monthly': 'Monthly',
    'habits.streak': 'Streak',
    'notes.title': 'Notes',
    'notes.addNote': 'Add note',
    'notes.noteTitle': 'Note title',
    'notes.noteContent': 'Note content',
    'notes.search': 'Search notes',
    'shopping.title': 'Shopping',
    'shopping.addItem': 'Add item',
    'shopping.itemName': 'Item name',
    'shopping.quantity': 'Quantity',
    'shopping.price': 'Price',
    'shopping.category': 'Category',
    'shopping.purchased': 'Purchased',
    'chat.title': 'AI Chat',
    'chat.typeMessage': 'Type a message...',
    'chat.send': 'Send',
    'chat.aiAssistant': 'AI Assistant',
    'mood.title': 'Mood',
    'mood.today': "Today's mood",
    'mood.addEntry': 'Add entry',
    'mood.note': 'Note',
    'meals.title': 'Meal Planner',
    'meals.addMeal': 'Add meal',
    'meals.mealName': 'Meal name',
    'meals.calories': 'Calories',
    'meals.mealType': 'Meal type',
    'error.network': 'Network error',
    'error.auth': 'Authentication error',
    'error.validation': 'Validation error',
    'error.unknown': 'Unknown error',
    'error.emailRequired': 'Email is required',
    'error.passwordRequired': 'Password is required',
    'error.invalidEmail': 'Invalid email',
    'error.weakPassword': 'Password is too weak',
    'success.saved': 'Saved',
    'success.deleted': 'Deleted',
    'success.updated': 'Updated',
    'success.added': 'Added',
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.tomorrow': 'Tomorrow',
    'time.thisWeek': 'This week',
    'time.thisMonth': 'This month',
    'time.lastWeek': 'Last week',
    'time.lastMonth': 'Last month',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Aufgaben',
    'nav.shopping': 'Einkauf',
    'nav.habits': 'Gewohnheiten',
    'nav.notes': 'Notizen',
    'nav.budget': 'Budget',
    'nav.plan': 'Plan',
    'nav.calendar': 'Kalender',
    'nav.meals': 'Mahlzeiten',
    'nav.mood': 'Stimmung',
    'nav.chat': 'Chat',
    'nav.settings': 'Einstellungen',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.loginWithGoogle': 'Mit Google anmelden',
    'auth.createAccount': 'Konto erstellen',
    'auth.alreadyHaveAccount': 'Haben Sie bereits ein Konto?',
    'auth.dontHaveAccount': 'Haben Sie kein Konto?',
    'auth.signUp': 'Registrieren',
    'auth.signIn': 'Anmelden',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.close': 'Schließen',
    'common.confirm': 'Bestätigen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.done': 'Fertig',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'dashboard.title': 'Willkommen zurück',
    'dashboard.subtitle': 'Ihr persönlicher Produktivitätsassistent',
    'dashboard.todayTasks': 'Heutige Aufgaben',
    'dashboard.upcomingEvents': 'Bevorstehende Ereignisse',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.recentNotes': 'Aktuelle Notizen',
    'dashboard.budgetOverview': 'Budgetübersicht',
    'dashboard.habitProgress': 'Gewohnheitsfortschritt',
    'tasks.title': 'Aufgaben',
    'tasks.addTask': 'Aufgabe hinzufügen',
    'tasks.taskTitle': 'Aufgabentitel',
    'tasks.description': 'Beschreibung',
    'tasks.dueDate': 'Fälligkeitsdatum',
    'tasks.priority': 'Priorität',
    'tasks.status': 'Status',
    'tasks.high': 'Hoch',
    'tasks.medium': 'Mittel',
    'tasks.low': 'Niedrig',
    'tasks.completed': 'Abgeschlossen',
    'tasks.pending': 'Ausstehend',
    'tasks.inProgress': 'In Bearbeitung',
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Passen Sie LifeFlow an Ihre Bedürfnisse und Vorlieben an.',
    'settings.profile': 'Profil',
    'settings.appearance': 'Erscheinungsbild',
    'settings.notifications': 'Benachrichtigungen',
    'settings.privacy': 'Datenschutz',
    'settings.language': 'Sprache',
    'settings.ai': 'Künstliche Intelligenz',
    'settings.ai.subtitle': 'Verwalten Sie KI-Stärke und Assistenten',
    'settings.notifications.subtitle': 'Benachrichtigungen und Erinnerungen verwalten',
    'settings.appearance.subtitle': 'Dunkles Design, helles Design und Akzentfarben',
    'settings.theme': 'Theme',
    'settings.export': 'Daten exportieren',
    'settings.about': 'Über',
    'settings.help': 'Hilfe',
    'settings.subscription': 'Abonnement',
    'settings.subscription.subtitle': 'LifeFlow Premium - Aktiv',
    'settings.defaultUser': 'LifeFlow Benutzer',
    'settings.editProfile': 'Profil bearbeiten',
    'budget.title': 'Budget',
    'budget.income': 'Einnahmen',
    'budget.expenses': 'Ausgaben',
    'budget.balance': 'Saldo',
    'budget.addTransaction': 'Transaktion hinzufügen',
    'budget.amount': 'Betrag',
    'budget.category': 'Kategorie',
    'budget.description': 'Beschreibung',
    'calendar.title': 'Kalender',
    'calendar.today': 'Heute',
    'calendar.week': 'Woche',
    'calendar.month': 'Monat',
    'calendar.addEvent': 'Ereignis hinzufügen',
    'calendar.eventTitle': 'Ereignistitel',
    'calendar.startTime': 'Startzeit',
    'calendar.endTime': 'Endzeit',
    'habits.title': 'Gewohnheiten',
    'habits.addHabit': 'Gewohnheit hinzufügen',
    'habits.habitName': 'Gewohnheitsname',
    'habits.frequency': 'Häufigkeit',
    'habits.daily': 'Täglich',
    'habits.weekly': 'Wöchentlich',
    'habits.monthly': 'Monatlich',
    'habits.streak': 'Serie',
    'notes.title': 'Notizen',
    'notes.addNote': 'Notiz hinzufügen',
    'notes.noteTitle': 'Notiztitel',
    'notes.noteContent': 'Notizinhalt',
    'notes.search': 'Notizen suchen',
    'shopping.title': 'Einkauf',
    'shopping.addItem': 'Artikel hinzufügen',
    'shopping.itemName': 'Artikelname',
    'shopping.quantity': 'Menge',
    'shopping.price': 'Preis',
    'shopping.category': 'Kategorie',
    'shopping.purchased': 'Gekauft',
    'chat.title': 'KI-Chat',
    'chat.typeMessage': 'Nachricht eingeben...',
    'chat.send': 'Senden',
    'chat.aiAssistant': 'KI-Assistent',
    'mood.title': 'Stimmung',
    'mood.today': 'Heutige Stimmung',
    'mood.addEntry': 'Eintrag hinzufügen',
    'mood.note': 'Notiz',
    'meals.title': 'Mahlzeitenplaner',
    'meals.addMeal': 'Mahlzeit hinzufügen',
    'meals.mealName': 'Mahlzeitenname',
    'meals.calories': 'Kalorien',
    'meals.mealType': 'Mahlzeitenart',
    'error.network': 'Netzwerkfehler',
    'error.auth': 'Authentifizierungsfehler',
    'error.validation': 'Validierungsfehler',
    'error.unknown': 'Unbekannter Fehler',
    'error.emailRequired': 'E-Mail ist erforderlich',
    'error.passwordRequired': 'Passwort ist erforderlich',
    'error.invalidEmail': 'Ungültige E-Mail',
    'error.weakPassword': 'Passwort ist zu schwach',
    'success.saved': 'Gespeichert',
    'success.deleted': 'Gelöscht',
    'success.updated': 'Aktualisiert',
    'success.added': 'Hinzugefügt',
    'time.today': 'Heute',
    'time.yesterday': 'Gestern',
    'time.tomorrow': 'Morgen',
    'time.thisWeek': 'Diese Woche',
    'time.thisMonth': 'Dieser Monat',
    'time.lastWeek': 'Letzte Woche',
    'time.lastMonth': 'Letzter Monat',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('lifeflow-language') : null;
    if (saved && Object.keys(translations).includes(saved)) return saved as Language;
    const browserLang = typeof navigator !== 'undefined' ? navigator.language.split('-')[0] : 'en';
    if (Object.keys(translations).includes(browserLang)) return browserLang as Language;
    return 'pl';
  });

  useEffect(() => {
    localStorage.setItem('lifeflow-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback((key: string): string => {
    const translation = (translations[language] as Record<string, string>)?.[key];
    if (!translation) {
      const fallback = (translations.pl as Record<string, string>)?.[key];
      return fallback || key;
    }
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
